project:
  type: website
  output-dir: docs

website:
  title: "Quarto Website"
  navbar:
    left:
        - href: index.qmd
          text: Home
        - about.qmd
        - newpage.qmd
        - contact.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



